### ISSUE TITLE
Spook 5.0.0 input_number services incompatible with Home Assistant Core 2026.8.0, 2026.8.1

### ISSUE THREAD

**Issue by KruseLuds** [frenck/spook#1406]
### What version of Spook are you using?

5.0.0

### What version of Home Assistant are you using?

2026.8.0, 2026.8.1

### The problem

After upgrading Home Assistant Core from 2026.7.4 to 2026.8.0, the
input_number.increment service fails when Spook 5.0.0 is enabled.

Environment:

Home Assistant Core: 2026.8.0 (discovered under 2026.8.0, retested under 2026.8.1)
Previous working Core version: 2026.7.4
Spook: 5.0.0
Installation type: Home Assistant OS
Architecture: aarch64

Observed error:

'InputNumber' object has no attribute '_step'

The error occurs both:

1. From an automation using input_number.increment
2. When input_number.increment is called manually from Developer Tools

The automation itself triggers correctly, but stops at the increment action.

I reviewed the Spook input_number service files and found obsolete private
InputNumber attributes in four files:

custom_components/spook/ectoplasms/input_number/services/increment.py
custom_components/spook/ectoplasms/input_number/services/decrement.py
custom_components/spook/ectoplasms/input_number/services/min.py
custom_components/spook/ectoplasms/input_number/services/max.py

Current Spook references:

increment.py:
- entity._step
- entity._current_value
- entity._maximum

decrement.py:
- entity._step
- entity._current_value
- entity._minimum

min.py:
- entity._minimum

max.py:
- entity._maximum

Home Assistant Core 2026.8.0 now uses the NumberEntity native-value API:

- entity.native_step
- entity.native_value
- entity.native_min_value
- entity.native_max_value
- entity.async_set_native_value(...)

The Home Assistant InputNumber implementation itself now stores values in
_attr_native_value, _attr_native_min_value, _attr_native_max_value, and
_attr_native_step, while exposing the public native_* properties.

Suggested modernization:

entity._step
    -> entity.native_step

entity._current_value
    -> entity.native_value

entity._minimum
    -> entity.native_min_value

entity._maximum
    -> entity.native_max_value

entity.async_set_value(...)
    -> entity.async_set_native_value(...)

The increment and decrement implementations should also account for the type
of native_value and native_step being optional, although InputNumber instances
normally populate them.

Related Home Assistant Core issue:

https://github.com/home-assistant/core/issues/178276

Disabling Spook and restarting Home Assistant restores the built-in
input_number services.

Suggested replacement logic for increment:

step = entity.native_step
value = entity.native_value

if step is None or value is None:
    raise ValueError(f"Unable to determine value or step for {entity.entity_id}")

amount = call.data.get("amount", step)

if not math.isclose(amount % step, 0, abs_tol=1e-9):
    raise ValueError(
        f"Amount {amount} not valid for {entity.entity_id}, "
        f"it needs to be a multiple of {step}"
    )

await entity.async_set_native_value(
    min(value + amount, entity.native_max_value)
)

For decrement, possibly use the equivalent max(value - amount, entity.native_min_value)

### Anything in the logs? Paste it here!

```plain text

```

**Comment by FrankTub** [comment]
Having the same issue, was also first on course that this would be a core issue. Hopefully this can be quickly resolved since spook does have a lot of nice advantages 😄

**Comment by KruseLuds** [comment]
"since spook does have a lot of nice advantages" AMEN TO THAT!

**Comment by ghosty-be** [comment]
hmm asked claude first if he could figure it out since there is something in changelog about input_number changes for 2026.8.0 but I should first have consulted the logs, there it shows that it trips over:
line 37 in file /config/custom_components/spook/ectoplasms/input_number/services/increment.py
which led me here.

**Comment by jmcruvellier** [comment]
> Having the same issue, was also first on course that this would be a core issue. Hopefully this can be quickly resolved since spook does have a lot of nice advantages 😄 

I had the same feeling that it was a core issue, until I saw in an issue discussion that disabling Spook solve it...
Hope there will be a fix soon because this utility is very helpful!

**Comment by KruseLuds** [comment]
This is still a problem in 2026.8.1

**Comment by ciux23** [comment]
Confirming this affects me too — Spook 5.0.0 on HA Core 2026.8.0 (HA OS, aarch64).

Two of my scripts that use input_number.increment/input_number.decrement in a repeat loop (gradual volume ramp-up/down for a wake-up/bedtime automation) started failing with the same 'InputNumber' object has no attribute '_step' traceback pointing at custom_components/spook/ectoplasms/input_number/services/increment.py (and presumably decrement.py).

The analysis and proposed fix in this issue (mapping _step/_current_value/_minimum/_maximum to the new native_step/native_value/native_min_value/native_max_value API, per the NumberEntity migration in HA Core 2026.8) matches what I found investigating on my end. As a workaround I rewrote my two affected scripts to use input_number.set_value with a template-computed value instead of increment/decrement, which avoids Spook's broken service entirely — but obviously the native services should work again without needing that.

Thanks for the detailed root-cause writeup, it made diagnosing my own instance much faster 🙏

**Comment by epposan** [comment]
I only noticed this **_step** issue because on one of my systems solar production remained low, even though there was plenty of sun.

I have an automation the starts reducing solar production if the line voltage reaches certain limits (to avoid a total shutdown).

In this case, it reached a limit at which a fixed (low) level was set, but after that none of the **increase steps** succeeded.

The error was shown in the logs, but I normally don't check them daily.

**Comment by Stephan-4711** [comment]
is there a plan, when this will be fixed? it breaks a lot of my automations, where I use input.number and I also want to use spook. disable spook fixed it so far.

**Comment by jmcruvellier** [comment]
> is there a plan, when this will be fixed? it breaks a lot of my automations, where I use input.number and I also want to use spook. disable spook fixed it so far.

There is a [pull request](https://github.com/frenck/spook/pull/1407) fixing this issue which is pending for final approvals... let's wait

**Comment by spideysri2802** [comment]
any workaround until this PR is merged?

**Comment by ccle610** [comment]
Deactivation of Spook will solve this problem ;-(
For me, roll back to HA 2026.7.4 was helpful.

**Comment by jdeluyck** [comment]
Having patience. It'll get fixed.

**Comment by Test-subj** [comment]
If you're extremely impatient, you can download the 4 files that are changed in the PR (https://github.com/Dillton/spook/tree/main/custom_components/spook/ectoplasms/input_number/services) and drop them into your local spook folder (config/custom_components/spook/ectoplasms/input_number/services) 

I can confirm that it fixed things on my end.

**Comment by KruseLuds** [comment]
@frenck any update on this one so I can re-enable my spook integration? :-)

**Comment by frenck** [comment]
Fixed in #1407, which is on `main` now. Not in a release yet, so it ships with the next one.

Thanks for the detailed report, the retest against 2026.8.1 and the exact error made this quick to pin down.

../Frenck

<p>
  <a href="https://www.linkedin.com/in/frenck/"><img src="https://github.com/frenck/frenck/raw/main/images/linkedin.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://youtube.com/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/youtube.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://bsky.app/profile/frenck.social"><img src="https://github.com/frenck/frenck/raw/main/images/bluesky.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://fosstodon.org/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/mastodon.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.instagram.com/frenck/"><img src="https://github.com/frenck/frenck/raw/main/images/instagram.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.threads.net/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/threads.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.facebook.com/frenck.dev/"><img src="https://github.com/frenck/frenck/raw/main/images/facebook.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://x.com/frenck"><img src="https://github.com/frenck/frenck/raw/main/images/x.svg" width="18" height="18"></a>
  &nbsp;&nbsp;
  <a href="https://www.tiktok.com/@frenck.nl"><img src="https://github.com/frenck/frenck/raw/main/images/tiktok.svg" width="18" height="18"></a>
</p>

Blogging my personal ramblings at <a href="https://frenck.dev">frenck.dev</a>

**Comment by KruseLuds** [comment]
> Fixed in [#1407](https://github.com/frenck/spook/pull/1407), which is on `main` now. Not in a release yet, so it ships with the next one.
> 
> Thanks for the detailed report, the retest against 2026.8.1 and the exact error made this quick to pin down.
> 
> ../Frenck
> 
> [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/linkedin.svg">](https://www.linkedin.com/in/frenck/)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/youtube.svg">](https://youtube.com/@frenck)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/bluesky.svg">](https://bsky.app/profile/frenck.social)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/mastodon.svg">](https://fosstodon.org/@frenck)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/instagram.svg">](https://www.instagram.com/frenck/)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/threads.svg">](https://www.threads.net/@frenck)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/facebook.svg">](https://www.facebook.com/frenck.dev/)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/x.svg">](https://x.com/frenck)    [<img alt="" width="18" height="18" src="https://github.com/frenck/frenck/raw/main/images/tiktok.svg">](https://www.tiktok.com/@frenck.nl)
> 
> Blogging my personal ramblings at [frenck.dev](https://frenck.dev)

You da man!
