### ISSUE TITLE
'InputNumber' object has no attribute '_step'

### ISSUE THREAD

**Issue by klaptafel** [frenck/spook#1403]
### What version of Spook are you using?

5.0.0

### What version of Home Assistant are you using?

2026.8.0

### The problem

When running `input_number.increment` or `input_number.decrement` they give an `Error: 'InputNumber' object has no attribute '_step'`. 

But the target entity definitely has a step configured. 

Same issue: https://github.com/home-assistant/core/issues/178276 

### Anything in the logs? Paste it here!

```plain text
Logger: homeassistant.components.script.ventilatie_temp_high
Source: helpers/script.py:573
Integration: Script (documentation, issues)
First occurred: 09:22:34 (1 occurrence)
Last logged: 09:22:34

Ventilatie: Temp high: Error executing script. Unexpected error for call_service at pos 1: 'InputNumber' object has no attribute '_step'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 573, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1081, in _async_step_call_service
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 683, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2961, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 3004, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 906, in entity_service_call
    response_data = await _async_handle_entity_calls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 785, in _async_handle_entity_calls
    single_result = await entity.async_request_call(_with_context(entity, coro))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1710, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 780, in _with_context
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 864, in _handle_single_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/spook/ectoplasms/input_number/services/increment.py", line 37, in async_handle_service
    amount = call.data.get("amount", entity._step)  # noqa: SLF001
                                     ^^^^^^^^^^^^
AttributeError: 'InputNumber' object has no attribute '_step'. Did you mean: 'step'?
```

**Comment by madrani79** [comment]
Same issue here. Error started in the logs directly after updating HA core to 2026.8

**Comment by tureka** [comment]
Same here. Hope for solution before winter. I use it for heating.

**Comment by WesWesthaver** [comment]
Does anyone know if/when this issue will be addressed? Spook has been a useful addition to my Home Assistant system and I'd hate to give it up.
